[package]
name = "activities"
version = "0.1.0"
edition = "2018"

[lib]
name = "demo"
path="src/lib/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
